#!/bin/bash

setxkbmap -layout pl
xwallpaper --zoom ~/Pictures/bg.jpg

dunst &

while true
do
	VOL="🔊 $(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')"
    TIME=$(date +"%d.%m.%Y %H:%M")
    WIFI="$(awk '/^\s*w/ { print "📶", int($3 * 100 / 70) "% " }' /proc/net/wireless)"
	BAT="🔋 $(cat /sys/class/power_supply/BAT1/capacity)%"

	xsetroot -name "$VOL | $WIFI | $BAT | $TIME"
	sleep 30s
done &

exec dwm
