set number relativenumber
syntax on

" Move .viminfo file
set viminfo+=n~/.local/share/viminfo

" Check spelling
"set spell
set spelllang=en,pl

" make cursor stay more in the middle
set so=12

" Enable color themes
"if !has('gui_running')
"    set t_Co=256
"endif
" Enable true colors
"set termguicolors
" Vim colorsheme
"colorscheme desert
"set background=dark

" Highlight search
"set hlsearch
set incsearch

" Set tabs and indent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set smartindent

" Format and encoding
set fileformat=unix
set encoding=utf-8

" Show matching brackets when text indicator is over them
set showmatch

" Mouse support
set mouse=a

" Allow saving of files as sudo when I forgot to start vim using sudo.
cmap w!! w !sudo tee > /dev/null %
cmap x!! x !sudo tee > /dev/null %

" highlight current line
"set cursorline
":highlight  Cursorline cterm=bold ctermbg=black
